### ISSUE TITLE
Cannot open builder in macos

### ISSUE THREAD

**Issue by khairulimran-97** [booleanbites/houzi-builder-release#1]
<img width="244" alt="image" src="https://github.com/booleanbites/houzi-builder-release/assets/105085586/7e2352f7-3498-44a4-9792-5e7b699acc52">

**Comment by AdilSoomro** [comment]
Press ctrl and then click on the icon. It should show a menu. Click open from the menu.

See attached:

<img width="641" alt="open-on-mac" src="https://github.com/booleanbites/houzi-builder-release/assets/856233/df96ec2c-f3b6-4e7b-96e0-2b5d04d50027">

**Comment by AdilSoomro** [comment]
Marking this issue as closed. Please contact us again if issue persists.
