### ISSUE TITLE
Houzi Builder  windows not opening

### ISSUE THREAD

**Issue by 2EuroGang** [booleanbites/houzi-builder-release#2]
Trying to open software but its not working, its freez here trying diferent pc same problem
![Unbenannt](https://github.com/user-attachments/assets/196adc58-f716-46c8-930d-0720281ecdf2)

**Comment by AdilSoomro** [comment]
Can you confirm if you have installed the Houzez CRM plugin. If no, can you install and try again?

**Comment by 2EuroGang** [comment]
After install CRM .All working
